#!/usr/bin/env bash
systemctl disable tlp-switch-daemon.service
rm /usr/local/bin/tlp-switch-user
rm /usr/local/sbin/tlp-switch
rm /usr/local/sbin/tlp-switch-daemon
rm /etc/systemd/system/tlp-switch-daemon.service
rm -rf /usr/local/share/tlp-switch
